name = "alineados-webapp"
compatibility_date = "2024-01-01"
main = ".svelte-kit/output/server/index.js"

[build]
command = "npm run build"

[assets]
directory = ".svelte-kit/output/client"
binding = "ASSETS" 